### ISSUE TITLE
Bootswatch css not loaded

### ISSUE THREAD

**Issue by devleaks** [raoul2000/yii2-bootswatch-asset#3]
I noticed that thomaspark/bootswatch installs bootswatches in @app/components.
(Is it because of thomaspark/bootswatch/composer.json that specifies that "type": "component" that files are loaded in @app/components?)

I needed to set the source path to '@app/components/bootswatch' because
	const VENDOR_ALIAS = '@vendor/thomaspark/bootswatch';
points to empty directory.

So before I AppAsset::register, I call
Yii::$container->set('raoul2000\bootswatch\BootswatchAsset', ['sourcePath' => '@app/components/bootswatch']);

P.

**Comment by raoul2000** [comment]
Hi, 

I've just installed dev-master and nothing is installed in @app/components... I have no idea what could cause such a behavior. Normally, thomaspark/bootswatch installs in vendor.

Can you try again from a fresh Yii2 app ?

**Comment by devleaks** [comment]
I composer removed thomaspark/bootswatch and raoul2000/yii2-bootswatch-asset and reinstalled raoul2000/yii2-bootswatch-asset and they are placed in appropriate folder.
In the meantime, I updated fxp/composer-asset-plugin from beta3 to 1.0.0. Don't know it it is related.
Thanks. P.
