### ISSUE TITLE
update to bootswatch 4.1.1 

### ISSUE THREAD

**Issue by fakname8** [raoul2000/yii2-bootswatch-asset#7]
You will update bootswatch for 4.1.1 ?

thank you :)

**Comment by fakname8** [comment]
Sorry, it did not work as well as I expected.

Sorry my bad english.

**Comment by raoul2000** [comment]
ok I will make some tests to see what can be done.
don't worry, your english is just fine 😉

**Comment by raoul2000** [comment]
ok I will make some tests to see what can be done.
don't worry, your english is just fine 😉

**Comment by raoul2000** [comment]
after some reading I have understood that BS4 is not supported yet in stable. The [yii2-bootstrap4](https://github.com/yiisoft/yii2-bootstrap4) extension has no release version so I think I will wait a little bit beofre upgrading **yii2-bootswatch-asset**.

But I'll keep an eye on it ...

**Comment by fakname8** [comment]
ok, thank you!! =))

**Comment by raoul2000** [comment]
Please note that I have release the [yii2-bootswatch4-asset](https://github.com/raoul2000/yii2-bootswatch4-asset) extension that is (as you may have understood) dedicated to be used with Bootstrap 4.

Cheers
